apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-user
rules:
  - apiGroups: ["apps",""]
    resources: ["services","deployments","pods"]
    verbs: ["get","list","watch","create","delete","patch"]
    
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-user
  namespace: jenkins

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-user
subjects:
- kind: ServiceAccount
  namespace: jenkins
  name: jenkins-user
  